# FSDEXT2.mak - makefile for VxD FSDEXT2


FSD_DIR = ..
WIN_DIR = e:\win95

DEVICENAME = TSDEXT2
DYNAMIC = 1
FRAMEWORK = C
DEBUG = 1
OBJECTS = tsdext2.OBJ tsdutil.OBJ
XFLAGS = -I$(FSD_DIR)

!include $(VTOOLSD)\include\vtoolsd.mak
!include $(VTOOLSD)\include\vxdtarg.mak

tsdext2.OBJ:	tsdext2.c tsdext2.h $(FSD_DIR)\iosmgr.h
tsdutil.OBJ:	tsdutil.c tsdutil.h tsdext2.h $(FSD_DIR)\iosmgr.h


install:
	copy $(DEVICENAME).vxd $(WIN_DIR)\system\iosubsys

