# spy.mak - makefile for VxD spy

DEVICENAME = spy
DYNAMIC = 1
FRAMEWORK = C
DEBUG = 1
OBJECTS = SPY.OBJ VXDDEBUG.OBJ

!include $(VTOOLSD)\include\vtoolsd.mak
!include $(VTOOLSD)\include\vxdtarg.mak

SPY.OBJ:	SPY.c SPY.h vxddebug.h
VXDDEBUG.OBJ:	VXDDEBUG.c vxddebug.h spy.h